name: Unit tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Setup conda env
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          activate-environment: test
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          set -eux
          conda activate test
          conda install pytorch cpuonly -c pytorch-nightly
          pip install -r requirements.txt
          pip install -r dev-requirements.txt
          pip install --no-build-isolation -e ".[dev]"
      - name: Run unit tests with coverage
        shell: bash -l {0}
        run: |
          set -eux
          conda activate test
          pytest --timeout=300 --cov=. --cov-report xml -vv -rA -m "not gpu_only" tests
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v2
